name: "Lightning Talks: Speaker Tracker"
description: Track what information has been collected from each speaker and where they are in the process of preparing for Lightning Talks
title: "Speaker: "
labels: ["Lightning Talks"]
assignees:
  - meg-gutshall
  - shelleymcq
body:
  - type: markdown
    attributes:
      value: |
        ## Speaker Tracker

        Check off/fill in the items below as they are received/updated. Any notes or attachments should be added as comments on the issue. This issue will live in the Lightning Talks project and help us work toward organizing everyone for presentation day.
  - type: markdown
    attributes:
      value: "### Lightning Talk Idea Form Info"
  - type: input
    attributes:
      label: Slack Username
      value: "@"
    validations:
      required: true
  - type: input
    attributes:
      label: Tentative Talk Title
  - type: checkboxes
    attributes:
      label: Talk Title Follow-up
      options:
        - label: Talk title updated
        - label: Talk title confirmed
  - type: textarea
    attributes:
      label: Talk Description
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Talk Description Follow-up
      options:
        - label: Talk description updated
        - label: Talk description confirmed
  - type: dropdown
    attributes:
      label: Mentor Requested
      description: This speaker requested to be paired with a mentor
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  - type: markdown
    attributes:
      value: "### Information Requirements"
  - type: dropdown
    attributes:
      label: Speaker Bio on File
      description: This speaker has a bio on file with Virtual Coffee
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Speaker Bio Follow-up
      options:
        - label: Sent speaker bio create link
        - label: Sent speaker bio update link
        - label: Speaker bio confirmed
  - type: checkboxes
    attributes:
      label: Speaker Info
      description: Check off each box as the information is collected and add to the issue as an attachment or comment
      options:
        - label: Talk Slides
        - label: Length of Talk (in minutes)
  - type: dropdown
    attributes:
      label: Video Recording
      description: This speaker will be pre-recording their Lightning Talk
      multiple: false
      options:
        - "No"
        - "Yes"
      default: 0
    validations:
      required: true
  - type: checkboxes
    attributes:
      label: Video Recording Follow-up
      options:
        - label: Video recording confirmed
  - type: markdown
    attributes:
      value: "### Communications & Setup"
  - type: checkboxes
    attributes:
      label: Mentorship
      description: "If the speaker requested a mentor, check the box below and enter the mentor's name once they've been paired"
      options:
        - label: Introduced to mentor via Slack message
        - label: Mentor added to `#lightning-talk-mentors` Slack channel
  - type: input
    attributes:
      label: Mentor Name
  - type: checkboxes
    attributes:
      label: Communications
      description: Check off each box as the tasks are completed
      options:
        - label: Added to `#lightning-talks` Slack channel
        - label: Contacted to confirm Lightning Talk Idea Submission data
        - label: Contacted to confirm/update/create speaker bio
        - label: Contacted to schedule A/V check
        - label: Conducted A/V check
        - label: Created intro slide
