name: 'Lightning Talks: Speaker Info'
description: Track what information has been collected from each speaker
title: 'Speaker: '
labels: ['Lightning Talks']
body:
  - type: checkboxes
    attributes:
      label: Speaker Info
      description: Check off each box as the information is collected
      options:
        - label: Talk title
        - label: Talk description
        - label: Talk slides
        - label: Length of talk
        - label: Video recording of talk (optional)
        - label: Headshot
        - label: Speaker bio
        - label: Contact links (optional)
